### ISSUE TITLE
Update to 1.21

### ISSUE THREAD

**Issue by KarmaCatMC** [drusin/mvinv-importer#1]
Hello, it would be really helpful if you could update this plugin so it works with MC 1.21 as between 1.16 and the new version the names for enchantments and some other stuff have been changed so the plugin sadly doesn't work in version 1.21. If there is any way I can help you in updating it don't hesitate to ask, as it would save me hours of manual labor if the plugin were to be update

Thanks in advance

**Comment by drusin** [comment]
Hey, I can take a look during the weekend or so. Since I did not use Multiverse since 4 years ago when I migrated using this plugin, can you upload an example json file so I don't have to set it up myself?

**Comment by KarmaCatMC** [comment]
Yeah for sure, thanks a lot

**Comment by KarmaCatMC** [comment]
[_Karmacat_.json](https://github.com/user-attachments/files/17589656/_Karmacat_.json)

**Comment by drusin** [comment]
Hey, can you have a go if [0.1.0](https://github.com/drusin/mvinv-importer/releases/tag/0.1.0) is working for you? With the provided json some names look broken, are you using any plugins for styling item names?

**Comment by KarmaCatMC** [comment]
So it restores the Items without any issues beside the name not showing up right, I used Essentials to rename my Items, so that may be why

**Comment by KarmaCatMC** [comment]
But it only seems to affect myself as im the only one who used essentials to rename my Items

**Comment by KarmaCatMC** [comment]
Oh, I believe the contents of shulkers doesnt get recovered

**Comment by drusin** [comment]
Ok, then I'll not bother anymore with the item names, but will have another look at shulkers

**Comment by KarmaCatMC** [comment]
Thanks a lot

**Comment by drusin** [comment]
Hey, I could spend some time on it today and dealing with shulkers turned out to be way more complicated than I thought. I'm making progress, but it's getting very late now - I think I should have it working this week hopefully.

**Comment by KarmaCatMC** [comment]
that would be great

**Comment by KarmaCatMC** [comment]
Also is there any way to bulkrestore inventories so I dont have to do each one by hand?

**Comment by drusin** [comment]
Hey, bad news - I'm running into more and more roadblocks with the shulker issue and decided to give up on it now.

I wrote the plugin in a quick and dirty manner for my family server four years ago and open sourced it, in case it can help anyone else. Since migrating away from Multiverse back then I did not have a reason to engage with this topic anymore. I already spent a bunch of hours working on it and I'm at a point where I'm not interested in spending more time on it.

Sorry.

**Comment by KarmaCatMC** [comment]
No, thats completely understandable and fine. However as I already asked is there any way to bulkrestore the inventories?

**Comment by drusin** [comment]
No, there currently isn't a way for that, mostly because the restoring only works for online players so there would need to be some logic to remember which player was already imported and which not yet.

**Comment by KarmaCatMC** [comment]
okay
